title: Gaminax
description: Topics in Web Publishing, Formatting, Editors and Programming Languages.
remote_theme: jekyll/minima
google_analytics: UA-73093345-1
show_downloads: false
github_username: gaminax
github: [metadata]
exclude: [docs]
source: docs
baseurl: /computing
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-asciidoc
asciidoc:
    ext: ad, adoc, asciidoc

