[Home/](../../../index.html)
[Computing/](../../index.html)
[Web/](../index.html)
Jekyll

## Jekyll
Jekyll(2014) is a static web site generator.

The styles allowed by Github are: Architect, Cayman, Dinky, Hacker, Leap day, Merlot, Midnight, Minima, Minimal, Modernist, Slate, Tactile, Time machine.

Installing the github-pages ruby gem ensures that the web pages generated are the same as thos generated by the github web server.

